name: 'CI + CD'

on:
    push:
        branches:
            - main

jobs:
    code_checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm install @actions/core
              
            - name: Run code checks
              run: node ./scripts/code_checks.js
              shell: bash

    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x
            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                  token: '${{ secrets.GITHUB_TOKEN }}'

            - run: 
                   pip install mkdocs
                   pip install mkdocs-material
                   pip install mike
                   pip install mkdocs-git-revision-date-plugin
                   pip install mkdocs-git-revision-date-localized-plugin
            - name: Clear mk-docs branch
              run: mike delete --all

            - run: mike deploy rep Repentance -t Repentance
            - run: mike set-default rep

            - name: Deploy AB+ Docs
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ab_plus

            - run: mike deploy abp Afterbirth+ -t Afterbirth+

            - name: Copy old ab+ docs and index.html
              uses: andstor/copycat-action@v3
              with:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  src_path: /.
                  dst_owner: wofsauge
                  dst_repo_name: IsaacDocs
                  src_branch: old_docs
                  dst_branch: gh-pages
                  commit_message: Finished updating Github-Pages
            - run: git push
