name: Code quality checker

on:
  pull_request:
    branches: [ main ]

jobs:
    code_checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm install @actions/core
              
            - name: Run code checks
              run: node ./scripts/code_checks.js
              shell: bash
